<a href="https://colab.research.google.com/github/Tiberu2611/github/blob/master/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

cú pháp của hàm apply_along_axis() là numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs) 
trong đó  

*   func1d là hàm chấp nhận mảng 1 chiều 
*   axis là trục mà mảng bị cắt
*   args là đối số bổ xung hàm func1d 
*   kwargs là các đối số được đặt tên bổ sung cho func1d

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
A = np.random.randint(1,20, size = (15,17))
print(A)

[[ 5 13  4  5 12 16 13  1  4 13 15  8  2 10  3  9  4]
 [17  2 13 10 14  6  3 15 19  9  2  7 18 15 17 11 15]
 [ 3 18  2  2 10 15 19 11 17  1  2  1 13 19 14 14  5]
 [18  9  9  8  8 10 16 11  4  1  1  2  2  4  3 15 10]
 [10  2  4  7 17 18  1  2 19  9 14 17 17 13  8 17 13]
 [18  4  9 14 19 16 19  4 16 18  4  2  3  6 15 16 19]
 [11 12  9  1  8  5  6  2 15  5 18 14 10 11 17 10 16]
 [12 12  2 15  7 13 14 15 16  8  8  9  4  5  4 10  2]
 [ 2 18 14 14  8  6 12  9 10  1  7 15  9 13  4 16  1]
 [10  4 18 11  1  3 19  9  2  5 11  8 13  8  5 17 13]
 [18 18 11  5 12 10  1 10  8 18 15 12 10 14 15  7 18]
 [ 6 12  6  7 10 15 18  3  8 11 16  7 18  6 11 16 14]
 [ 3 18 14  8 16 11 15  9 17  1  1 17 18 12 19 19  5]
 [ 8 17 18 12 12  5  5 19  6  2 16 14  1  2  3 18  3]
 [17 11 19  2 17 10 16 16  8 17 11 18 19 14 13 19 14]]


Bài 3 Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tim_gia_tri_lon_nhat = np.apply_along_axis(max, 1, A)
print(tim_gia_tri_lon_nhat)

[16 19 19 18 19 19 18 16 18 19 18 18 19 19 19]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tim_gia_tri_nho_nhat = np.apply_along_axis(min, 0,A)
print(tim_gia_tri_nho_nhat)

[2 2 2 1 1 3 1 1 2 1 1 1 1 2 3 7 1]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tinh_tong = np.apply_along_axis(sum, 1, A)
print(tinh_tong)

[137 193 166 131 188 202 170 156 159 157 202 184 203 161 241]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong2(A): 
    s = 0
    for i in range(0,len(A)): 
        if i % 2 != 0: 
            s += A[i]
    return s
b = np.apply_along_axis(tinh_tong2, 0, A)
print(b)
c = np.apply_along_axis(tinh_tong2, 1, A)
print(c)

[ 89  60  75  77  71  68  94  76  71  54  58  49  59  46  58 103  76]
[ 75  75  81  60  85  80  60  87  92  65  94  77  95  89 107]
