<a href="https://colab.research.google.com/github/Tiberu2611/github/blob/master/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np


Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [ ]:
a = np.arange(5, 6, 2, dtype=int)
a1 = np.transpose(a)
b = np.linspace(5,11, 7)
b1 = np.transpose(b)
c = np.logspace(1.0, 7.0, num=7, base = 2)
c1 = np.transpose(c)
d = np.random.rand(1,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(C.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[5]
1 1 (1,) (1,)
[ 5.  6.  7.  8.  9. 10. 11.]
1 1 (7,) (7,)
[  2.   4.   8.  16.  32.  64. 128.]
1 1 (7,) (7,)
[[0.50048262 0.17819005 0.61518994 0.28593286 0.57711881 0.97181638
  0.09327609]]
2 2 (1, 7) (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận a10x7 với giá trị các phần tử của ma trận a
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận a và ma trận aT

In [ ]:
A = np.arange(0, 70, 1)
A.shape = (10,7)
A1 = np.transpose(A)
B = np.linspace(0, 70, 70)
B.shape = (10,7)
B1 = np.transpose(B)
C = np.logspace(0, 70, num=70, base = 2)
C.shape = (10,7)
C1 = np.transpose(C)
D = np.random.rand(1, 70)
D.shape = (10,7)
D1 = np.transpose(D)
print(A)
print(A.ndim, A1.ndim, A.shape, A1.shape)
print(B)
print(B.ndim, B1.ndim, B.shape, B1.shape)
print(C)
print(C.ndim, C1.ndim, C.shape, C1.shape)
print(D)
print(D.ndim, D1.ndim, D.shape, D1.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2 2 (10, 7) (7, 10)
[[ 0.          1.01449275  2.02898551  3.04347826  4.05797101  5.07246377
   6.08695652]
 [ 7.10144928  8.11594203  9.13043478 10.14492754 11.15942029 12.17391304
  13.1884058 ]
 [14.20289855 15.2173913  16.23188406 17.24637681 18.26086957 19.27536232
  20.28985507]
 [21.30434783 22.31884058 23.33333333 24.34782609 25.36231884 26.37681159
  27.39130435]
 [28.4057971  29.42028986 30.43478261 31.44927536 32.46376812 33.47826087
  34.49275362]
 [35.50724638 36.52173913 37.53623188 38.55072464 39.56521739 40.57971014
  41.5942029 ]
 [42.60869565 43.62318841 44.63768116 45.65217391 46.66666667 47.68115942
  48.69565217]
 [49.71014493 50.72463768 51.73913043 52.75362319 53.76811594 54.7826087
  55.79710145]
 [56.8115942  57.82608696 58

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận a ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [ ]:
A = np.arange(0, 70, 1)
A.shape = (10,7)
A1 = A.flatten()
A2 = A1.reshape(10,7)
B = np.linspace(0, 69, 70)
B.shape = (10,7)
B1 = B.flatten()
B2 = B1.reshape(10,7)
C = np.logspace(0, 10, num=70, base = 2)
C.shape = (10,7)
C1 = C.flatten()
C2 = C1.reshape(10,7)
D = np.random.rand(1, 70)
D.shape = (10,7)
D1 = D.flatten()
D2 = D1.reshape(10,7)
print(A)
print(A1)
print(A2)
print(B)
print(B1)
print(B2)
print(C)
print(C1)
print(C2)
print(D)
print(D1)
print(D2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68.

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [ ]:
A = np.logspace(0, 149, num=150)
A.shape = (10,15)
A3 = A[3,:]
A5 = A[:,5]
print(A)
print(A3)
print(A5)

[[1.e+000 1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008
  1.e+009 1.e+010 1.e+011 1.e+012 1.e+013 1.e+014]
 [1.e+015 1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023
  1.e+024 1.e+025 1.e+026 1.e+027 1.e+028 1.e+029]
 [1.e+030 1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038
  1.e+039 1.e+040 1.e+041 1.e+042 1.e+043 1.e+044]
 [1.e+045 1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053
  1.e+054 1.e+055 1.e+056 1.e+057 1.e+058 1.e+059]
 [1.e+060 1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068
  1.e+069 1.e+070 1.e+071 1.e+072 1.e+073 1.e+074]
 [1.e+075 1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083
  1.e+084 1.e+085 1.e+086 1.e+087 1.e+088 1.e+089]
 [1.e+090 1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098
  1.e+099 1.e+100 1.e+101 1.e+102 1.e+103 1.e+104]
 [1.e+105 1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113
  1.e+114 1.e+115 1.e+116 1.e+117 1.e+118 1.e+119]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [27]:
def tinh_tb(a): 
    s = 0
    for i in range(0,len(a)): 
        s += a[i]
    tb = s/len(a)
    return tb
a = np.arange(0,150,1)
a.shape = (15,10)
b = np.apply_along_axis(tinh_tb, 0, a)
c = np.apply_along_axis(tinh_tb, 1, a)
print(a)
print("tính giá trị trung bình trên cột", b)
print("tính giá trị trung bình trên hàng", c)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
độ lệch chuẩn trên cột [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
độ lệch chuẩn trên hàng [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]


In [38]:
def median(a):
    a = sorted(a)
    n = len(a)
    if n % 2 == 1:
        return a[n//2]
    else:
        i = n//2
        return (a[i - 1] + a[i])/2

a = np.arange(0,150,1)
a.shape = (15,10)
b = np.apply_along_axis(median, 0, a)
c = np.apply_along_axis(median, 1, a)
print(a)
print("tính giá trị trung vị trên cột", b)
print("tính giá trị trung vị trên hàng", c)


[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
tính giá trị trung vị trên cột [70 71 72 73 74 75 76 77 78 79]
tính giá trị trung vị trên hàng [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]


In [40]:
def var(a):
  s = 0
  for i in range(0,len(a)): 
      s += (a[i]**2)
  ps = s/len(a)
  return ps

a = np.arange(0,150,1)
a.shape = (15,10)
b = np.apply_along_axis(var, 0, a)
c = np.apply_along_axis(var, 1, a)
print(a)
print("tính phương sai trên cột", b)
print("tính phương sai trên hàng", c)



[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
tính phương sai trên cột [6766.66666667 6907.66666667 7050.66666667 7195.66666667 7342.66666667
 7491.66666667 7642.66666667 7795.66666667 7950.66666667 8107.66666667]
tính phương sai trên hàng [   28.5   218.5   608.5  1198.5  1988.5  2978.5  4168.5  5558.5  7148.5
  8938.5 10928.5 13118.5 15508.5 18098.5 20888.5]


In [39]:
from math import sqrt
def std(a):
  s = 0
  for i in range(0,len(a)): 
      s += (a[i]**2)
  dlc = sqrt(s/len(a))
  return dlc

a = np.arange(0,150,1)
a.shape = (15,10)
b = np.apply_along_axis(std, 0, a)
c = np.apply_along_axis(std, 1, a)
print(a)
print("tính độ lệch chuẩn trên cột", b)
print("tính độ lệch chuẩn trên hàng", c)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
tính độ lệch chuẩn trên cột [82.2597512  83.11237373 83.96824797 84.82727549 85.68936146 86.55441448
 87.42234649 88.29307259 89.1665109  90.04258252]
tính độ lệch chuẩn trên hàng [  5.33853913  14.7817455   24.66779277  34.61935875  44.59260028
  54.57563559  64.56392181  74.55534857  84.54880248  94.54364072
 104.53946623 114.53602054 124.53312812 13