<a href="https://colab.research.google.com/github/Tiberu2611/github/blob/master/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
A = np.random.randint(1,20, size = (15,17))
print(A)

[[17 19  7  7  3  2  6 19 17  4  8  8 19  1  2  7  4]
 [17  2 12  1  5 16 18 10  7 15  5 15 14  8 14 12 14]
 [ 4 19 18 17  9  1  9 16  6 19  6 15  9 18 13 13 15]
 [17  1 16 12 19  1  4  7 11  4  3  7 17  7  1  3  4]
 [ 1 13 11  4 15  5  8  8  4 16  6 18  9  1 13  6  4]
 [11  8 17  4  2 13  4 10  6 12 16 10 13 14 11 16 19]
 [12  8  7 16  2 11 12 15 16 17 11  7 14  4 17 15  1]
 [ 3 16  7  7 17 15 12  4 14 13 19  6  1  9 12  5  1]
 [12  1  8  2 12  3 15  4 15  2 19 16  4 18  2  9 13]
 [12  2 15 19  9 13 16  8  4 16 11  4 17 11 18 15 19]
 [18  2  9 17  6 11  5  3 10  3 14 13 14  2  1  7 14]
 [13  8 13  6 12  9  1 17  2  1 13 11 18  4  3  5  5]
 [15 11  6  7  8  4 15 19  6  7 10  9  4 18 15 15 19]
 [10 17 10  1  5 16 12 12  8 11  9  3 19 14  1  3 12]
 [18 11 14 17 13  5  8  6 15  3 19 11 18  6 11  4  5]]


Bài 3 Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tim_gia_tri_lon_nhat = np.apply_along_axis(max, 1, A)
print(tim_gia_tri_lon_nhat)

[19 18 19 19 18 19 17 19 19 19 18 18 19 19 19]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tim_gia_tri_nho_nhat = np.apply_along_axis(min, 0,A)
print(tim_gia_tri_nho_nhat)

[1 1 6 1 2 1 1 3 2 1 3 3 1 1 1 3 1]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
tinh_tong = np.apply_along_axis(sum, 1, A)
print(tinh_tong)

[150 185 207 134 142 186 185 161 155 209 149 141 188 163 184]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.