<a href="https://colab.research.google.com/github/Tiberu2611/github/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Bài 1: Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
A = np.random.randint(1,10, size = (7,5))
print(A)

[[4 6 2 4 8]
 [5 7 3 6 4]
 [6 6 2 5 1]
 [7 4 3 9 3]
 [2 4 8 2 4]
 [4 6 1 6 2]
 [4 5 8 3 9]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j. Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)). Kết quả xuất ra màn hình.

In [ ]:
A = np.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
A = np.random.randint(10,size=(7,7))
print(A)

Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0 trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j. Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [2]:
A = np.zeros((6,6),int)
np.fill_diagonal(A,15)
print(A)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường chéo đều bằng 0. Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm numpy.triu(). Kết quả xuất ra màn hình.

In [6]:
a= np.random.randint(10,size=(8,8))
b=np.triu(a,-1)
print(b)

[[0 2 0 2 2 1 0 9]
 [4 2 5 7 3 9 1 6]
 [0 7 8 8 6 6 9 2]
 [0 0 6 7 3 7 7 3]
 [0 0 0 7 6 5 1 6]
 [0 0 0 0 6 1 5 2]
 [0 0 0 0 0 1 2 1]
 [0 0 0 0 0 0 6 2]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [5]:
a= np.random.randint(10,size=(8,8))
b=np.tril(a)
print(b)

[[9 0 0 0 0 0 0 0]
 [9 7 0 0 0 0 0 0]
 [4 1 4 0 0 0 0 0]
 [3 3 4 8 0 0 0 0]
 [9 4 0 8 7 0 0 0]
 [3 4 9 5 4 8 0 0]
 [6 2 7 0 2 5 7 0]
 [3 5 3 5 6 4 2 3]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận I9 . Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [4]:
a = np.identity(9)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận:#Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

In [3]:
a= np.random.randint(5,size=(6,7))    
b= np.random.randint(5,size=(6,7))
print("Ma trận thứ 1:\n",a)
print("Ma trận thứ 2:\n",b)
print("Tổng 2 ma trận:\n",a+b)

Ma trận thứ 1:
 [[3 0 3 4 0 4 4]
 [2 0 4 1 3 1 2]
 [1 1 1 1 3 3 1]
 [1 1 1 2 4 2 1]
 [4 0 1 2 2 1 0]
 [2 0 3 3 3 4 0]]
Ma trận thứ 2:
 [[0 0 4 1 4 1 4]
 [2 1 1 3 3 4 4]
 [4 2 3 2 1 2 0]
 [4 0 3 3 1 1 0]
 [4 4 2 2 3 4 3]
 [4 3 2 2 1 2 1]]
Tổng 2 ma trận:
 [[3 0 7 5 4 5 8]
 [4 1 5 4 6 5 6]
 [5 3 4 3 4 5 1]
 [5 1 4 5 5 3 1]
 [8 4 3 4 5 5 3]
 [6 3 5 5 4 6 1]]


Hãy sinh ngẫu nhiên 1 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình.

In [7]:
x= np.random.randint(5,size=(5,8))    
print("Ma trận ngẫu nhiên:\n",x)
n= int(input("Mời nhập 1 số: "))
print("Tích vô hướng 1 số với ma  trận:\n", n*x)

Ma trận ngẫu nhiên:
 [[3 0 2 2 4 4 3 0]
 [0 3 3 4 2 2 0 2]
 [0 3 0 4 2 0 4 3]
 [3 1 3 3 3 2 4 4]
 [3 3 0 2 4 4 2 0]]
Mời nhập 1 số: 5
Tích vô hướng 1 số với ma  trận:
 [[15  0 10 10 20 20 15  0]
 [ 0 15 15 20 10 10  0 10]
 [ 0 15  0 20 10  0 20 15]
 [15  5 15 15 15 10 20 20]
 [15 15  0 10 20 20 10  0]]


Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

In [8]:
y= np.random.randint(5, size = (3,7))
print("Ma trận được tạo ngẫu nhiên:\n",y)
t=np.transpose(y)
print("Ma trận sau khi được chuyển vị:\n",t)

Ma trận được tạo ngẫu nhiên:
 [[4 1 1 2 2 4 2]
 [4 4 0 3 2 0 0]
 [1 2 0 1 0 1 1]]
Ma trận sau khi được chuyển vị:
 [[4 4 1]
 [1 4 2]
 [1 0 0]
 [2 3 1]
 [2 2 0]
 [4 0 1]
 [2 0 1]]


Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3, tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình. Gợi ý: sử dụng hàm numpy.dot()

In [9]:
a= np.random.randint(5,size=(5,7))
b= np.random.randint(5,size=(7,3))
print("Tích 2 ma trận :\n", np.dot(a,b))

Tích 2 ma trận :
 [[38 36 40]
 [26 38 46]
 [34 28 40]
 [30 24 32]
 [28 30 36]]


Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi ý: sử dụng hàm numpy.linalg.inv()

In [10]:
a= np.random.randint(5,size=(5,5))
print("Ma trận lúc đầu: \n",a)
b= np.linalg.inv(a)
print("Ma trận khả nghịch: \n",b)

Ma trận lúc đầu: 
 [[3 4 2 4 4]
 [3 2 2 4 0]
 [1 3 0 3 4]
 [1 0 4 1 3]
 [4 2 2 3 4]]
Ma trận khả nghịch: 
 [[ 0.10576923 -0.08653846 -0.32692308 -0.19230769  0.36538462]
 [ 0.88461538 -0.26923077 -0.46153846 -0.15384615 -0.30769231]
 [ 0.28365385 -0.00480769 -0.24038462  0.21153846 -0.20192308]
 [-0.66346154  0.45192308  0.59615385  0.11538462 -0.01923077]
 [-0.19230769 -0.11538462  0.23076923  0.07692308  0.15384615]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

*   Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
*   Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên 1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.



In [11]:
a = np.random.randint(5,size=(1,8))
print(a)
b= np.random.randint(5,size=(8,1))
print(b)

[[0 0 0 0 1 3 1 1]]
[[2]
 [0]
 [0]
 [2]
 [1]
 [3]
 [3]
 [2]]
